AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customers-api-gateway

  Sample SAM Template for customers-api-gateway

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: customersapi
    Runtime: java11
    MemorySize: 512
    Timeout: 20
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        CUSTOMERS_TABLE: !Ref CustomersTable

Resources:
  CustomersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.CreateCustomerLambda::createCustomer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
      Architectures:
        - x86_64
      Events:
        CustomersEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customers
            Method: POST

  ReadCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.ReadCustomerLambda::getCustomers
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CustomersTable
      Architectures:
        - x86_64
      Events:
        CustomersEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customers
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomersApi:
    Description: "API Gateway endpoint URL for Prod stage for Customers function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customers/"
  CreateCustomerFunction:
    Description: "CreateCustomer Lambda Function ARN"
    Value: !GetAtt "CreateCustomerFunction.Arn"
  ReadCustomerFunction:
    Description: "ReadCustomer Lambda Function ARN"
    Value: !GetAtt "ReadCustomerFunction.Arn"
  CreateCustomerFunctionIamRole:
    Description: "Implicit IAM Role created for CreateCustomer function"
    Value: !GetAtt CreateCustomerFunctionRole.Arn
